// #import "axis-styles/barycentric-2d/barycentric-2d.typ"
#import "axis-styles/polar-2d/polar-2d.typ"
#import "axis-styles/orthorect-2d/orthorect-2d.typ"
// #import "axis-styles/barycentric-2d/barycentric-2d.typ"
// #import "axis-styles/barycentric-2d/barycentric-2d.typ"